version: 2
updates:
- package-ecosystem: maven
  directory: "/java"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.google.errorprone:error_prone_annotations
    versions:
    - 2.5.1
  - dependency-name: com.google.guava:guava-testlib
    versions:
    - 30.1-jre
  - dependency-name: org.apache.felix:maven-bundle-plugin
    versions:
    - 5.1.1
